runtime: nodejs  # Node.js version
env: flex
runtime_config:
      operating_system: "ubuntu22"
entrypoint: npm start  # Ensure your package.json has a start script

handlers:
  - url: /.*
    script: auto

